using ExampleApp.IntegrationTests.Environment;

namespace ExampleApp.IntegrationTests;

public class DuplicatePermissionValidationTestsImpl() : DuplicatePermissionValidationTests(TestEnvironmentImpl.Instance.RootServiceProvider);